[build-system]
requires = ["setuptools>=61.0.0", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "lsy_drone_racing"
version = "0.0.1"
description = "LSY Autonomous Drone Racing Project Course"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
]

dependencies = [
    "fire >= 0.6.0",
    "munch >= 4.0.0",
    "numpy >= 1.24.1, < 2.0.0",
    "pandas >= 2.0.3",
    "pybullet >= 3.2.6",
    "PyYAML >= 6.0.1",
    "rospkg >= 1.5.1",
    "scipy >= 1.10.1",
    "gymnasium == 0.29.1",
    "toml >= 0.10.2",
    "casadi >= 3.6.5",
    "swig >= 4.2.1",            # Required for pycffirmware
]

[project.optional-dependencies]
test = ["pytest>=8.0.0"]
rl = ["stable-baselines3"]


[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
lsy_drone_racing = ["sim/assets/*.dae", "sim/assets/*.urdf"]

[tool.pytest.ini_options]
markers = ["unit", "integration"]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".git-rewrite",
    ".ipynb_checkpoints",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "site-packages",
    "venv",
    "docs/conf.py",
]

line-length = 100
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "D", "TCH", "ANN"]
ignore = ["ANN101", "ANN401"]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"benchmarks/*" = ["D100", "D103"]
"tests/*" = ["D100", "D103", "D104"]


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-annotations]
suppress-dummy-args = true
suppress-none-returning = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = true
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
