[dynamics_info]
interface = "Mellinger" # "Mellinger", "Thrust"
ts = 0.016666
n_horizon = 60
controlType = "Thrusts" # "Thrusts", "Torques", "RPMs"
dynamicsType= "Quaternion" # "Quaternion", "Euler", "MPCC"
useControlRates = false # always true for MPCC dynamics
t_predict = 0 # Solve optimization problem for state predicted into the future, set t_predict to 0 when not used
useDrags = true # Whether to include drag forces in the dynamics
reference = "hermite_spline" # "spline", "polynomial", # which type of reference trajectory to use
start_controller = true # Whether to use a start controller until a certain height has been reached
[dynamics_info.ukf_info]
useUKF=false
measurement_noise=0.01 # std
action_disturbance=0.001 # std
process_noise= 0.01 # std

[cost_info] # Optimize through TurBO
cost_type = "linear"
Qs_pos = 2 #4
Qs_vel = 1.0
Qs_rpy = 1.6
Qs_drpy = 0.1 # 0.05
Qs_quat = 0.01 #0.1
Qt_pos = 10
Qt_vel = 0.004
Qt_rpy = 0.08
Qt_drpy = 2
Qt_quat = 2
Rs = 0.2 #0.2
Rd = 0.01 # Control rates

[cost_info_mpcc]
cost_type = "mpcc"
Ql = 1 # lag weights
Qc = 1 # contour weights
Qw = 1 # ang vel weights
Qmu = 1 # L1 dprogress weight
Rdf = 0.01 # thrust rate weights
Rdprogress = 0.01

[constraints_info]
useObstacleConstraints = true
obstacle_diameter = 0.15
tunnel_constraints = true # only for MPCC dynamics
Wn = 0.3
Wgate = 0.1

[optimizer_info]
useSoftConstraints = true
softPenalty = 1e3
useGP = false
useZoro = false
export_dir ="generated_code/mpc"
json_file = "acados_ocp.json"

[solver_options]
ipopt.print_level= 0
ipopt.tol= 1e-4
ipopt.max_iter=30
ipopt.linear_solver= "mumps"
acados_nlp_solver= "SQP_RTI"
acados_integrator= "ERK"
acados_cost_discretization= "EULER"
acados_qp_solver= "PARTIAL_CONDENSING_HPIPM"
acados_globalization= "MERIT_BACKTRACKING"
acados_tol= 1e-3
acados_qp_tol= 1e-3
acados_build=true
acados_generate=true

[hyperparameters]
[hyperparameters.linear_cost]
